export const SIGN_IN_DATA = [
  {
    id: 1,
    email: 's00001@gsm.hs.kr',
    password: '0000',
    name: '국선생',
    role: 'teacher',
    subject: 'KOREAN',
    grade: 1,
    classNum: 1,
    number: null,
  },
  {
    id: 2,
    email: 's00002@gsm.hs.kr',
    password: '0000',
    name: '위선생',
    role: 'teacher',
    subject: 'WEE',
    grade: null,
    classNum: null,
    number: null,
  },
  {
    id: 3,
    email: 's22024@gsm.hs.kr',
    password: '0000',
    name: '서주미',
    role: 'student',
    grade: '2',
    classNum: '2',
    number: '10',
    major: 'Front-End Developer',
    info: '안녕하세요! 프론트엔드 개발자를 희망하는 서주미입니다!',
    github: 'https://github.com/SeoJumee',
    blog: 'https://github.com/SeoJumee/TIL',
    insta: 'https://www.instagram.com/juuuuuum_/',
  },
  {
    id: 4,
    email: 's22001@gsm.hs.kr',
    password: '0000',
    name: '김하온',
    role: 'student',
    grade: '1',
    classNum: '1',
    number: '6',
    major: 'Design',
    info: '반갑습니다 대한민국 1등 디자이너가 될 김하온입니다.',
    github: 'https://github.com/Haonee',
    blog: 'https://github.com//TIL',
    insta: 'https://www.instagram.com/mittoao/',
  },
  {
    id: 5,
    email: 's22002@gsm.hs.kr',
    password: '0000',
    name: '김희망',
    role: 'student',
    grade: '3',
    classNum: '4',
    number: '7',
    major: 'Back-End Developer',
    info: '안녕하세요 전 백엔드 1티어 개발자 k-hope입니다.',
    github: 'https://github.com/esperar',
    blog: 'https://github.com/esperar/estudy',
    insta: 'https://www.instagram.com/v.latile',
  },
  {
    id: 6,
    email: 's22003@gsm.hs.kr',
    password: '0000',
    name: '이태랑',
    role: 'student',
    grade: '2',
    classNum: '1',
    number: '15',
    major: 'Front-End Developer',
    info: '안녕하세요!! 새로운 것을 배우는 프론트엔드 이태랑 엔지니어입니다.',
    github: 'https://github.com/LeeTarang',
    blog: 'https://github.com/TRANG/TIL',
    insta: 'https://www.instagram.com/Trangg/',
  },
  {
    id: 7,
    email: 's22004@gsm.hs.kr',
    password: '0000',
    name: '정윤서',
    role: 'student',
    grade: '1',
    classNum: '4',
    number: '16',
    major: 'iOS Developer',
    info: '안녕하세요! iOS가 세상을 구한다! 세상을 구하는 정윤서입니다.',
    github: 'https://github.com/Yunnsit',
    blog: 'https://github.com/yooon/TIL',
    insta: 'https://www.instagram.com/JYSSS/',
  },
  {
    id: 8,
    email: 's22029@gsm.hs.kr',
    password: '0000',
    name: '김새미',
    role: 'student',
    grade: '3',
    classNum: '2',
    number: '6',
    major: 'iOS Developer',
    info: '안녕하세요! 성실한 개발자 김새미 입니다..',
    github: 'https://github.com/samiee',
    blog: 'https://github.com/samiee/TIL',
    insta: 'https://www.instagram.com/samiee/',
  },
  {
    id: 9,
    email: 's22021@gsm.hs.kr',
    password: '0000',
    name: '정민서',
    role: 'student',
    grade: '3',
    classNum: '4',
    number: '8',
    major: 'DevOps',
    info: '특별한 개발자 정민서 입니다..',
    github: 'https://github.com/minseo0128',
    blog: 'https://github.com/minseo0128/TIL',
    insta: 'https://www.instagram.com/minseo0128/',
  },

  {
    id: 10,
    email: 's22010@gsm.hs.kr',
    password: '0000',
    name: '이정우',
    role: 'student',
    grade: '3',
    classNum: '3',
    number: '11',
    major: 'Front-end Developer',
    info: '안녕하세요! 성장하는 프론트엔드 개발자 이정우 입니다.',
    github: 'https://github.com/LJWWW',
    blog: 'https://github.com/LJWWW/TIL',
    insta: 'https://www.instagram.com/LJWWW/',
  },

  {
    id: 11,
    email: 's22090@gsm.hs.kr',
    password: '0000',
    name: '박준서',
    role: 'student',
    grade: '1',
    classNum: '1',
    number: '7',
    major: 'iOS Developer',
    info: '안녕하세요. 정진하는 개발자 김주은입니다.',
    github: 'https://github.com/imskje',
    blog: 'https://github.com/imskjee/TIL',
    insta: 'https://www.instagram.com/imskje/',
  },

  {
    id: 12,
    email: 's22093@gsm.hs.kr',
    password: '0000',
    name: '신아인',
    role: 'student',
    grade: '1',
    classNum: '3',
    number: '18',
    major: 'iOS Developer',
    info: '안녕하세요! 정직한 iOS개발자 신아인 입니다.',
    github: 'https://github.com/orin',
    blog: 'https://github.com/orineeee/TIL',
    insta: 'https://www.instagram.com/orineww/',
  },
  {
    id: 13,
    email: 's22023@gsm.hs.kr',
    password: '0000',
    name: '김설희',
    role: 'student',
    grade: '2',
    classNum: '3',
    number: '16',
    major: 'DevOps',
    info: '안녕하세요! 노력하는 개발자 김설희 입니다..',
    github: 'https://github.com/sh_k',
    blog: 'https://github.com/sh_k/TIL',
    insta: 'https://www.instagram.com/sh_k/',
  },
  {
    id: 14,
    email: 's22039@gsm.hs.kr',
    password: '0000',
    name: '박주홍',
    role: 'student',
    grade: '3',
    classNum: '1',
    number: '11',
    major: 'Back-end Developer',
    info: '안녕하세요! 완벽한 개발자 노현주입니다.',
    github: 'https://github.com/ani_no',
    blog: 'https://github.com/ani_no/TIL',
    insta: 'https://www.instagram.com/ani_no/',
  },
];
