export const SIGN_IN_DATA = [
  {
    id: 1,
    email: 's00001@gsm.hs.kr',
    password: '0000',
    name: '국선생',
    role: 'teacher',
    subject: 'KOREAN',
    grade: 1,
    classNum: 1,
  },
  {
    id: 2,
    email: 's00002@gsm.hs.kr',
    password: '0000',
    name: '위선생',
    role: 'teacher',
    subject: 'WEE',
    grade: null,
    classNum: null,
  },
  {
    id: 3,
    email: 's22024@gsm.hs.kr',
    password: '0000',
    name: '서주미',
    role: 'student',
    grade: '2',
    classNum: '2',
    number: '9',
  },
  {
    id: 4,
    email: 's22001@gsm.hs.kr',
    password: '0000',
    name: '김하온',
    role: 'student',
    grade: '1',
    classNum: '1',
    number: '5',
  },
  {
    id: 5,
    email: 's22002@gsm.hs.kr',
    password: '0000',
    name: '김희망',
    role: 'student',
    grade: '3',
    classNum: '4',
    number: '8',
  },
  {
    id: 6,
    email: 's22003@gsm.hs.kr',
    password: '0000',
    name: '이태랑',
    role: 'student',
    grade: '2',
    classNum: '1',
    number: '15',
  },
  {
    id: 7,
    email: 's22004@gsm.hs.kr',
    password: '0000',
    name: '정윤서',
    role: 'student',
    grade: '1',
    classNum: '4',
    number: '16',
  },
];
