export const TASK_DATA = [
  {
    num: '1',
    title: '피그마프로토타이핑하기오늘까지해오세용',
    startDate: '2023.12.31',
    endDate: '2024.01.01',
    subject: 'HW',
    grade: '3',
    content: '제출 기한 엄수',
    file: '보고서 양식.hwp',
  },
  {
    num: '2',
    title: '네트워크와 데이터베이스 과목 보고서 과제 제출',
    startDate: '2023.12.31',
    endDate: '2024.01.08',
    subject: 'SW',
    grade: '2',
    content: '본인이 원하는 주제 택1',
    file: '보고서 양식.hwp',
  },
  {
    num: '3',
    title: '아두이노 기본기 학습',
    startDate: '2023.03.31',
    endDate: '2024.12.08',
    subject: 'HW',
    grade: '1',
    content: '아두이노 개념정리 보고서 작성',
    file: '보고서 양식.hwp',
  },
  {
    num: '4',
    title: 'PCB기판 마스터하기',
    startDate: '2023.04.23',
    endDate: '2024.12.12',
    subject: 'HW',
    grade: '3',
    content: '기판에 대해 마스터하고 작품 만들어오기',
    file: '기판 개념 정리본.hwp',
  },
  {
    num: '5',
    title: 'ORCAD 회로 만들기',
    startDate: '2023.09.02',
    endDate: '2024.11.11',
    subject: 'HW',
    grade: '2',
    content: 'ORCAD 회로 만들고 네트리스트 확인',
    file: 'ORCAD 회로순서 정리본.hwp',
  },
];
